### ISSUE TITLE
Clean up connectedChipReaders after disconnect

### ISSUE THREAD

**Issue by ish2028** [KeiserCorp/Keiser.Air.eChip.WebUSB#40]
After disconnecting the reader with a chip plugged in, clean up the `connectedChipReaders` array so that I know if there is a reader still plugged in. This is an issue because I can't update my UI correctly because it still thinks something is connected.

Another thing to think about is the order of execution on `onDisconnect` events.  Right now when a chip is plugged in with the reader, the events fire in this order

1. Chip Reader `onDisconnnect`
2. Chip `onDisconnect` 

It should go the other way around so the order makes sense.  My current logic would work if it went the other way around, which is how it was working in the past.  I'm not sure what changed that caused the order of execution to change.  But if you fix the array I can update my UI correctly or if you fix the chip `onDisconnect` firing order I wouldn't have to change anything in my current logic.

**Comment by bayssmekanique** [comment]
The order of events cannot be changed because the `onDisconnect` emitted by the `Chip` is driven by the `onDisconnect` event emitted by the `ChipReader`.  The order of events should not matter in this instance, however, as the `onDisconnect` event from the `ChipReader` should take precedence.
